

default:
    just --list

db-up:
    cd ../docker/auth && sudo docker compose -f docker-compose.insecure.yaml up 
db-reset:
    sqlx database reset
    cargo sqlx prepare
migrate:
    sqlx database setup
